#!/usr/bin/with-contenv bash

# fix for linting
declare config

# setup authentification
if [[ ${APP_USERNAME} && ${APP_PASSWORD} ]]; then
    htpasswd -b -c /config/nginx/.htpasswd ${APP_USERNAME} ${APP_PASSWORD}
else
    rm /config/nginx/.htpasswd 2> /dev/null
fi

# create symlinks
mkdir -p /app/www/public/media
symlinks=( \
/app/www/var \
/app/www/public/media
)

for i in "${symlinks[@]}"; do
    if [[ -e "$i" && ! -L "$i" && -e /config/"$(basename "$i")" ]]; then
        rm -Rf "$i"
        ln -s /config/"$(basename "$i")" "$i"
    fi
    if [[ -e "$i" && ! -L "$i" ]]; then
        mv "$i" /config/"$(basename "$i")"
        ln -s /config/"$(basename "$i")" "$i"
    fi
done

# setup permissions
chown -R abc:abc \
    /config \
    /photos
