#!/usr/bin/with-contenv bash

# fix for linting
declare config

# set version
PIXAPOP_COMMIT=$(cat /version.txt)

# install pixapop
if [[ ! -d "/config/www/pixapop/.git" ]]; then
	echo "fetching pixapop files from github 1"
	git clone https://github.com/bierdok/pixapop.git /config/www/pixapop
	git --git-dir=/config/www/pixapop/.git --work-tree=/config/www/pixapop checkout ${PIXAPOP_COMMIT}
fi
if [[ ${APP_ENV} == "prod" ]]; then
    cd /config/www/pixapop
    composer install
    yarn install
    yarn build
fi

# setup permissions
chown -R abc:abc /config/www/pixapop

# setup authentification
if [[ ${APP_USERNAME} && ${APP_PASSWORD} ]]; then
    htpasswd -b -c /config/nginx/.htpasswd ${APP_USERNAME} ${APP_PASSWORD}
else
    rm /config/nginx/.htpasswd 2> /dev/null
fi
